# Generated by Django 5.2.9 on 2025-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Các lựa chọn (JSON)'),
        ),
        migrations.AddField(
            model_name='response',
            name='response_data',
            field=models.JSONField(default=dict, verbose_name='Dữ liệu trả lời'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
