# Generated by Django 5.2.9 on 2025-12-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_question_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_quiz',
            field=models.BooleanField(default=False, verbose_name='Chế độ Quiz (có đáp án đúng / tính điểm)'),
        ),
    ]
