# Generated by Django 5.2.9 on 2025-12-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_is_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Các đáp án đúng (JSON)'),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, verbose_name='Điểm cho câu hỏi'),
        ),
    ]
