# Generated by Django 5.2.9 on 2025-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_review_response',
            field=models.BooleanField(default=True, help_text='Người trả lời có thể xem lại câu trả lời của mình sau khi gửi', verbose_name='Cho phép xem lại câu trả lời'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Câu hỏi tự luận'), ('single', 'Chọn một đáp án'), ('multiple', 'Chọn nhiều đáp án'), ('section', 'Tiêu đề'), ('description', 'Mô tả'), ('image', 'Hình ảnh'), ('video', 'Video')], default='single', max_length=20, verbose_name='Loại câu hỏi'),
        ),
    ]
