# Generated by Django 5.2.9 on 2025-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_survey_allow_review_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, help_text='Gửi email cảm ơn sau khi hoàn thành khảo sát (chỉ dùng khi tắt xem lại câu trả lời)', verbose_name='Gửi email xác nhận'),
        ),
    ]
