# Generated by Django 5.2.9 on 2025-12-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_survey_send_confirmation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='one_response_only',
            field=models.BooleanField(default=True, help_text='Mỗi người chỉ được trả lời khảo sát 1 lần duy nhất', verbose_name='Chỉ cho phép trả lời 1 lần'),
        ),
    ]
