# Generated by Django 5.2.9 on 2025-12-25 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_survey_starts_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=16, verbose_name='Vai trò')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='surveys.survey', verbose_name='Khảo sát')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phân quyền khảo sát',
                'verbose_name_plural': 'Phân quyền khảo sát',
                'constraints': [models.UniqueConstraint(fields=('survey', 'user'), name='uniq_survey_user_role')],
            },
        ),
    ]
