# Generated by Django 5.2.9 on 2025-12-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_surveycollaborator'),
        ('surveys', '0018_backfill_survey_collaborators'),
    ]

    operations = [
    ]
