# Generated by Django 5.2.9 on 2025-12-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0019_merge_20251225_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Câu hỏi tự luận"),
                    ("single", "Chọn một đáp án"),
                    ("multiple", "Chọn nhiều đáp án"),
                    ("upload", "Tải tệp (ảnh/video)"),
                    ("section", "Tiêu đề"),
                    ("description", "Mô tả"),
                    ("image", "Hình ảnh"),
                    ("video", "Video"),
                ],
                default="single",
                max_length=20,
                verbose_name="Loại câu hỏi",
            ),
        ),
        migrations.CreateModel(
            name="ResponseAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="response_uploads/%Y/%m/%d/", verbose_name="Tệp (ảnh/video)")),
                ("original_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Tên file gốc")),
                ("content_type", models.CharField(blank=True, default="", max_length=100, verbose_name="MIME type")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Thời gian upload")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_attachments",
                        to="surveys.question",
                        verbose_name="Câu hỏi",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="surveys.response",
                        verbose_name="Phản hồi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tệp đính kèm phản hồi",
                "verbose_name_plural": "Tệp đính kèm phản hồi",
            },
        ),
        migrations.AddConstraint(
            model_name="responseattachment",
            constraint=models.UniqueConstraint(
                fields=("response", "question"), name="uniq_response_question_attachment"
            ),
        ),
    ]


